### ISSUE TITLE
敢问大佬是高几

### ISSUE THREAD

**Issue by xizeyoupan** [Tymon42/study-makes-me-happy#6]
以及地区和选课（如果有）？
![](https://i.loli.net/2019/08/01/5d42dd78a19eb59954.jpg)

**Comment by harryisfish** [comment]
广东的，高三在读。我这一届是最后一届文理分科了（选的理科，没法复读的说）。。。。
可能会持续收集资料，不过平时在校不会时常维护这个repo。

你是高几？
Ples feel free to share this repo to ur friends, thank u. Have a nice day!

**Comment by harryisfish** [comment]
哦，后来我在GitHub上还看到你的笔记repo了，你才是大佬

**Comment by xizeyoupan** [comment]
> 你是高几？

浙江高三.物地技.一起加油吧

**Comment by harryisfish** [comment]
谢谢！明年六月等你好消息！
